extends: airbnb-base
env:
  jest: true
  node: true
  es6: true
parser: typescript-eslint-parser
plugins: [typescript]
rules: 
  no-undef: off
parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true