image:
  node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
    - npm install
    - echo "Build Successfull"

test:
  stage: test
  script:
    - npm test
    - echo "Test Successfull"

deploy:
  stage: deploy
  image: ruby:latest
  only:
    - master
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=flex-server-test --api-key=$HEROKU_API_KEY
    - echo "Deployment Successfull"
